# crée un fichier avec le contenu de la variable d'environnement APIS_KEYS en ".env" sur vscode avec la commande echo $APIS_KEYS > .env

name: 'APIs'

on:
  workflow_dispatch
  
env:
  APIS_KEYS: ${{ secrets.APIS_KEYS }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: recuperation dui secret
        working-directory: /
        run: echo $APIS_KEYS | base64 -d > test.txt

      - name: windows
        if: runner.os == 'Windows'
        working-directory: /
        run: |
          echo "Hello, Windows!"
          echo $APIS_KEYS > .env
          Get-Content .env