name: info

on: 
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]   

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Creat .env file
        run: |
          touch .env
          echo "APP_API_KEY=${{secrets.APIS_KEYS}}" >> .env
          cat .env
      - name: Deploy
        run: echo "Deploying!"