# crée un fichier avec le contenu de la variable d'environnement APIS_KEYS en ".env" sur vscode avec la commande echo $APIS_KEYS > .env

name: 'APIs'

on:
  workflow_dispatch:

permissions: read-all

# Environnement local pour les secrets.


env:
  APIS_KEYS: ${{ secrets.APIS_KEYS }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: create .env file
        run: echo ${{ secrets.APIS_KEYS }} > .env


