# crée un fichier avec le contenu de la variable d'environnement APIS_KEYS en ".env" sur vscode avec la commande echo $APIS_KEYS > .env

name: 'APIs'

on:
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier le code
        uses: actions/checkout@v4

      - name: Configurer les secrets
        env:
          MY_SECRET: ${{ secrets.APIS_KEYS }}
        run: echo "API_KEYS = $MY_SECRET" > .env

      - name: Exécuter votre tâche
        run: |
          # Utilisez le secret dans votre tâche ici
          # Par exemple, vous pouvez le passer à votre application ou à un script
          echo "Mon secret dans le fichier .env : $MY_SECRET"