# crée un fichier avec le contenu de la variable d'environnement APIS_KEYS de github action avec pwsh et curl directement dans le dossier de l'application
# https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables
# https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsrun


name: info

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
permissions:
  contents: write
  pull-requests: write
  issues: write


jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create file
      run: |
        $env:APIS_KEYS | Out-File -FilePath .\apis_keys.txt
        curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" -d '{"event_type": "info"}' https://api.github.com/repos/${{ github.repository }}/dispatches

    - name: Show content
      run: |
        Get-Content .\apis_keys.txt


    



