name: info

on: 
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    workflow_dispatch:
        inputs:
            parameter:
                description: 'Enter the API key'
    


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Creat .env file
        run: |
          echo "Creating .env file"
          echo file".env"
          touch .env
          echo "APP_API_KEY=${{secrets.APIS_KEYS}}" >> .env
          cat .env
      - name: Deploy
        run: echo "Deploying!"