name: info

on: 
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    workflow_dispatch:
        inputs:
            parameter:
                description: 'Enter the API key'
    


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Creat .env file
        shell: pwsh
        run: |
          echo "Creating .env file"
          echo file".env"
          new-item -path . -name .env -value "APP_API_KEY = ${{secrets.APIS_KEYS}}"
      - name: Deploy
        run: echo "Deploying!"