# crée un fichier avec le contenu de la variable d'environnement APIS_KEYS en ".env" sur vscode avec la commande echo $APIS_KEYS > .env

name: 'APIs'

on:
  workflow_dispatch
  
env:
  APIS_KEYS: "test"

permissions:
  contents: read
  pages: write
  id-token: write



jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: secret on local directory client # Create a secret on the local directory from windows
      shell: pwsh
      working-directory: client
      env:
        APIS_KEYS: ${{ secrets.APIS_KEYS }}
      run: echo $APIS_KEYS > /client/.env

