name: info

on: 
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    workflow_dispatch:
      inputs:
        APIS_KEYS:
          description: 'API keys'
          required: true
          default: 'default'
    


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Creat .env file
        run: |
          touch .env
          echo "APP_API_KEY=${{secrets.APIS_KEYS}}" >> .env
          cat .env
      - name: Deploy
        run: echo "Deploying!"