# crée un fichier avec le contenu de la variable d'environnement APIS_KEYS de github action avec pwsh et curl directement dans le dossier de l'application
# https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables
# https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsrun


name: info

on:
  push:
    branches:
      - main
        workflow_dispatch


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create file
      run: |
        echo ${{ secrets.APIS_KEYS }} > ./app/apis_keys.txt
        cat ./app/apis_keys.txt

    - name: List files
      run: ls ./app

    - name: Display content
      run: cat ./app/apis_keys.txt



