name: info

on: 
    workflow_dispatch:
    


jobs:
  build:
    runs-on: windows-latest
    steps:
      # crée un fichier avec le contenu de la variable d'environnement API_KEY en ".env"
      - name: Create .env file
        run: echo "API_KEY=${{ secrets.API_KEY }}" > .env
      # affiche le contenu du fichier ".env"
      - name: Show .env file
        run: type .env