# crée un fichier avec le contenu de la variable d'environnement APIS_KEYS en ".env" sur vscode avec la commande echo $APIS_KEYS > .env

name: 'APIs'

on:
  workflow_dispatch
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: recuperation dui secret
        run: echo $APIS_KEYS | base64 -d > test.txt