# crée un fichier avec le contenu de la variable d'environnement APIS_KEYS en ".env" sur vscode avec la commande echo $APIS_KEYS > .env

name: 'APIs'

on:
  workflow_dispatch
  
env:
  APIS_KEYS: "test"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: recuperation du secret
        run: echo $APIS_KEYS | base64 > ${{ github.workspace }}/.testing.txt
      - name: windows
        if: runner.os == 'Windows'
        run: |
          echo "Hello, Windows!"
          echo $APIS_KEYS > ./.env
          Get-Content .env

defaults:
  run:
    working-directory: /