name: laravel

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: create .env file
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: updtate composer
        working-directory: ./
        shell: bash
        run: composer update


  local:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: updtate composer
        working-directory: ./
        run: composer update

        