name: laravel
on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name : secrets
        run: vendor/bin/phpunit
        env:
          CI: true
          APIS_KEY: ${{ secrets.APIS_KEYS }}

      - name: Vérifier le code
        uses: actions/checkout@v4

      - name: Installer les dépendances
        run: |
          composer install
        shell: bash

      - name: Déployer
        run: |
          php artisan serve
        shell: bash

        