name: laravel
on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier le code
        uses: actions/checkout@v4

      - name: Installer les dépendances
        run: |
          composer install
        shell: bash

      - name: Déployer
        run: |
          php artisan deploy
        shell: bash

        