name: laravel

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name : secrets
        env:
          CI: true
          APIS_KEY: ${{ secrets.APIS_KEYS }}
        run: echo $APIS_KEY > .env

      - name: updtate composer
        shell: bash
        run: composer update

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
        
      - name: Install NPM dependencies
        run: npm install


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

    defaults:
      run:
        working-directory: ./public/index.php




        