name: laravel

on:
  workflow_dispatch


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name : secrets
        run: echo ${{ secrets.APIS_KEYS }}
        env:
          CI: true
          APIS_KEY: ${{ secrets.APIS_KEYS }}

      - name: updtate composer
        run: composer update

        