name: laravel

on:
  push:
    branches: ["master"]
  
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name : secrets
        run: echo ${{ secrets.APIS_KEYS }}
        env:
          CI: true
          APIS_KEY: ${{ secrets.APIS_KEYS }}

      - name: updtate composer
        run: composer update

        